image: edbizarro/gitlab-ci-pipeline-php:7.4
definitions:
  steps:
    - step: &yarn-install
        name: Yarn Installation
        caches:
          - node
        script:
          - yarn --version
          - yarn install --pure-lockfile
    - step: &yarn-build-develop
        name: Build development assets
        script:
          - yarn --version
          - yarn run development --progress false
        artifacts:
          - public/css/**
          - public/js/**
          - public/mix-manifest.json
    - step: &composer
        name: Composer
        caches:
          - composer
        script:
          - php -v
          - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-suggest
          - cp .env.example .env
          - php artisan key:generate
          - composer dumpautoload
        artifacts:
          - vendor/**
          - .env
    - step: &deploy-production
        name: Deploy on Production
        deployment: production
        trigger: manual
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.4
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            S3_BUCKET: $S3_BUCKET
            ACL: "public-read"
            LOCAL_PATH: "build"
pipelines:
  custom:
    deployment-to-prod:
      - step:
        script:
          - echo "Manual triggers for deployments are awesome!"
  branches:
    master:
    - parallel:
      - step: *composer
      - step: *deploy-production

